#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


# define tasks here
build (){
  echo "do build here"
}

run () {
  echo "do run here"
}

clean (){
  echo "do clean here"
}

list () {
  grep -E "()\ ?{$" "$0" | grep -v 'grep ' | awk '{print $1}' | sort
}

# main start here
command=${1:-""}

if [[ -n $(type -t "${command}") ]] && [[ $(type -t "${command}") = function ]]
then
  shift
  eval "$command" "$@"
  exit $?
fi

case "$command" in
  *)
    list
esac
